apiVersion: v1
kind: Service
metadata:
  name: sample-application
  labels:
    app: sample-application
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: sample-application
    tier: frontend
